services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=bookmarks
      - POSTGRES_PASSWORD=demo123
      - POSTGRES_DB=blog
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  pgdata: null